Traceback (most recent call last):
  File "/home/jsobolewski/mgr/myCode/samllNetCL_TaskIL.py", line 97, in <module>
    main(1)
  File "/home/jsobolewski/mgr/myCode/samllNetCL_TaskIL.py", line 94, in main
    train_losses, tasks_losses, exemplers = train_validation_all_classes(model, optimizer, tasks, device, epoch=1, log_interval = 10)
  File "/home/jsobolewski/mgr/myCode/samllNetCL_TaskIL.py", line 23, in train_validation_all_classes
    loss = F.cross_entropy(output, target)
  File "/home/jsobolewski/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 3026, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument target in method wrapper_nll_loss_forward)